apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postech-fastfood-cliente
  namespace: fiap-pos-tech
spec:
  selector:
    matchLabels:
      app: fiap-postech-fastfood-cliente
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-postech-fastfood-cliente
    spec:
      containers:
        - name: fiap-postech-fastfood-cliente
          image: 731362576078.dkr.ecr.us-east-1.amazonaws.com/fiap_postech_fastfood_cliente #pegar uri do repositório ECR
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # Requisição de CPU inicial
              memory: "512Mi"
            limits:
              cpu: "500m"  # Limite de CPU
              memory: "1Gi"
          env:
            - name: DB_HOST
              value: "jdbc:mysql://fiap-postech-db.cvnbiwixxp7f.us-east-1.rds.amazonaws.com:3306/clientes_db"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "password"
            - name: COGNITO_ID
              value: "17u8qu5sh0aega9rk7g4sh61i4"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-postech-service-cliente
spec:
  type: NodePort
  selector:
    app: fiap-postech-fastfood-cliente
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080




