apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postech-fastfood-cliente
  namespace: fiap-pos-tech
spec:
  selector:
    matchLabels:
      app: fiap-postech-fastfood-cliente
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-postech-fastfood-cliente
    spec:
      containers:
        - name: fiap-postech-fastfood-cliente
          image: 731362576078.dkr.ecr.us-east-1.amazonaws.com/fiap_postech_fastfood_cliente #pegar uri do repositório ECR
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # Requisição de CPU inicial
              memory: "512Mi"
            limits:
              cpu: "500m"  # Limite de CPU
              memory: "1Gi"
          env:
            - name: DB_HOST
              value: "db_host"
          ports:
            - containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#              httpHeaders:
#                - name: Check-Health-Header
#                  value: "application-up"
#            initialDelaySeconds: 120
#            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-postech-service-cliente
spec:
  selector:
    app: fiap-postech-fastfood-cliente
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80




